### ISSUE TITLE
Seems like "PyQt5" module issue in Anki 23.10

### ISSUE THREAD

**Issue by ManabBala** [giovannihenriksen/Anki-Simulator#74]
Debug info from anki startup:
```
Anki` 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.22631
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-03 20:20:02

When loading Anki Simulator:
Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "C:\Users\Mahadev\AppData\Roaming\Anki2\addons21\817108664\__init__.py", line 35, in <module>
    from PyQt5.QtWidgets import QAction
ModuleNotFoundError: No module named 'PyQt5'
```
Tried to just tweak the PyOt5 to PyQt6 , but seems like not working.

**Comment by ManabBala** [comment]
seems like the issue have has been fixed in the latest PRs but yet not updated/submitted to anki addon.
